### ISSUE TITLE
Unable to read file creation date from XMP tag - Dir Viewer File Tooltip

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#69]
Is it interpreting my audio file as image? I tried out the directory viewer and as soon as I hover over a file and it shows the information this error is thrown:

```
09:47.379 E [JavaFX Applicat] FileField - Unable to read file creation date from XMP tag for /home/janek/Daten/Musik/EnV/EnV - FireFrost.mp3
com.drew.imaging.ImageProcessingException: File format could not be determined
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:178)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:121)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:197)
        at sp.it.pl.util.access.fieldvalue.FileFieldKt.readXmpTimeCreated(FileField.kt:118)
        at sp.it.pl.util.access.fieldvalue.FileFieldKt.readTimeCreated(FileField.kt:96)
        at sp.it.pl.util.access.fieldvalue.FileFieldKt.access$readTimeCreated(FileField.kt:1)
        at sp.it.pl.util.access.fieldvalue.FileField$Companion$TIME_CREATED$1.invoke(FileField.kt:54)
        at sp.it.pl.util.access.fieldvalue.FileField$Companion$TIME_CREATED$1.invoke(FileField.kt:43)
        at sp.it.pl.util.access.fieldvalue.ObjectFieldBase.getOf(ObjectFieldBase.kt:25)
        at sp.it.pl.gui.pane.ActionPane.lambda$setDataInfo$3(ActionPane.java:375)
        at javafx.controls/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:593)
        at javafx.controls/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:578)
        at javafx.controls/javafx.scene.control.TableCell.updateItem(TableCell.java:646)
        at javafx.controls/javafx.scene.control.TableCell.indexChanged(TableCell.java:469)
        at javafx.controls/javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:120)
        at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:539)
        at javafx.controls/javafx.scene.control.skin.TableRowSkinBase.<init>(TableRowSkinBase.java:159)
        at javafx.controls/javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:89)
        at javafx.controls/javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:213)
        at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
        at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
        at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
        at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
        at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9515)
        at javafx.graphics/javafx.scene.Node.applyCss(Node.java:9602)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1715)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow.addLeadingCells(VirtualFlow.java:1947)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1250)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1211)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1218)
        at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:590)
        at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2507)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:410)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:409)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:436)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:319)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by sghpjuikit** [comment]
This one is bugging me for a while. It's easy to fix with an isDirectory check, but the problem is tthat would incur tremendous performance overhead for nothing.

**Comment by Xerus2000** [comment]
`isDirectory` check? Are you sure? I hovered over an audio file, not a directory

**Comment by sghpjuikit** [comment]
I meet this problem mostly with directories, but you are right, it should only be called for image or perhaps only psd files.

**Comment by sghpjuikit** [comment]
I have decided to solve this problem by not logging the exception when it is a result of calling the method on directory or non image file. Current implementation calls it for any File, thus it is not an exceptional state. The reasoning is weak, I'm aware of that, but the only solution would be to check ourselves, which is even worse. Ignoring the fact that we would be doing the same check twice (once ourselves and once done by the library), there is no way to make the same check as the library does, so this cant possibly work - it could break anytime the library would be updated.

The correct behavior is to catch the exception and 'handle' it - in this case correct handling is returning null, and not logging it. I will investigate whether this call could be enabled only for image files however.

**Comment by sghpjuikit** [comment]
Indeed the call can be avoided based on mime type, but we would have to know which formats the library supports. I'd rather always call the library and when it fails fallback to some other way to get creation date. In other words: I'm disabling the logging , but implementation stays.

**Comment by Xerus2000** [comment]
Sounds reasonable

**Comment by sghpjuikit** [comment]
Just a clarification: I will still only call this for image files as the library only works with that. That is a substantial reduction in cases this is called. This will be done once I confirm mime type handling is fine as it is. This can be closed.
