### ISSUE TITLE
CoreSerializer - Failed to deserialize MetadatasDB

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#71]
This error is encountered every time I launch the player. I suspect it is because of the update from Java 9 to Java 10.

When deserialization fails, the corrupt file should probably be deleted to prevent the failure from happening again.

```
39:23.605 E [ForkJoinPool.co] CoreSerializer - Failed to deserialize file=/home/janek/Projects/player/working dir/user/library/MetadatasDB to type=class sp.it.pl.audio.MetadatasDB
java.io.InvalidClassException: sp.it.pl.audio.tagging.Metadata; local class incompatible: stream classdesc serialVersionUID = 9158535142620934862, local class serialVersionUID = 65190842318266207
        at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
        at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1894)
        at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1763)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2051)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1585)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at java.base/java.util.HashMap.readObject(HashMap.java:1465)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2207)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2078)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1585)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at sp.it.pl.service.database.Db.getAllItems(Db.kt:134)
        at sp.it.pl.service.database.Db.updateInMemoryDbFromPersisted(Db.kt:122)
        at sp.it.pl.service.database.Db$init$2.run(Db.kt:48)
        at sp.it.pl.util.async.future.Fut.lambda$then$11(Fut.java:155)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by sghpjuikit** [comment]
This happens after the class changes. This case should be handled better (reporting to user), file deletion, etc. Data migration is impossile at this point, but it is possible to provide readResolve implementation that improves backward compatibilty (probably not good idea here. We should at least provide convenient way for the user to re-read the data from disc.

Anyway, an UX issue.

**Comment by sghpjuikit** [comment]
This problem occurs at deserialization time. Updating to Java may also trigger this, but I'm not 100% sure.

Yes the silent rebuild would be nice, but there is some legacy code that has to be taken care of first for this to be possible. Also raw Java serialization is gonna be gone soon and it was not the best solution to begin with - the idea is nice, but the output format should change. Kotlin serialization may come in handy here. There is enough for this to warrant a separate task. I can not work on this right now, but feel free to try something.

**Comment by sghpjuikit** [comment]
Note: The solution should also use safe-saving approach by using a temporary backup file. When the application is interrupted while saving, the previous data must not be lost.

**Comment by Xerus2000** [comment]
But since it is only cache, why even have UX for it at all? Can't it just do its stuff in the background and simply log it?

Another thing you should consider is having some live status update bar, i.e. in Intellij, but also in other music players like Amarok you have a little space at the bottom that informs you about important background jobs that are going on. Maybe that would be useful and it could be included in there. Some sort of internal notification and progress-reporting system.

**Comment by sghpjuikit** [comment]
This should no longer be an issue. Of course, if the underlying data classes change, deserialization will fail, but there is little to be done about that except error handling and supporting class evolution (which is not worth at the moment, since it requires wholly new serialization format). Closing.

**Comment by sghpjuikit** [comment]
See #155
