### ISSUE TITLE
Many plugins not loaded

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#96]
I can't use the player at all right now, since most plugins are not getting loaded any more.
```
11:53:59.763 [JavaFX Application Thread] INFO sp.it.pl.gui.UiManager - Registering skin: Flow
11:53:59.770 [JavaFX Application Thread] INFO sp.it.pl.gui.UiManager - Registering skin: Main
11:53:59.770 [JavaFX Application Thread] INFO sp.it.pl.gui.UiManager - Registering skin: Flow+
11:53:59.797 [JavaFX Application Thread] WARN FileMonitor - Recursive file watcher is not supported, using standard, file=/home/janek/daten/projects/player/working dir/skins
11:54:00.688 [JavaFX Application Thread] WARN Config - Unable to set value from text=Stars, reason=Object has no from-text converter
54:01.041 I [JavaFX-Launcher] App - JVM Args: [-Xms100m, -Xmx3g, --add-opens=java.base/java.util=ALL-UNNAMED, --add-opens=java.base/java.lang.reflect=ALL-UNNAMED, --add-opens=java.base/java.text=ALL-UNNAMED, --add-opens=java.base/java.util.stream=ALL-UNNAMED, --add-opens=java.base/java.lang=ALL-UNNAMED, --add-opens=java.desktop/java.awt.font=ALL-UNNAMED, --add-opens=javafx.controls/javafx.scene.control=ALL-UNNAMED, --add-opens=javafx.controls/javafx.scene.control.skin=ALL-UNNAMED, --add-opens=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED, --add-opens=javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED, --add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED, --add-opens=javafx.graphics/javafx.scene.image=ALL-UNNAMED, --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED, -Dfile.encoding=UTF-8, -Duser.country=US, -Duser.language=en, -Duser.variant]
Zeropad numbers - toggle
Show table controls - toggle
Settings use default
Rating allow partial - toggle
Hide unassigned shortcuts - toggle
Show guide on app start - toggle
Layout mode blur bgr - toggle
Developer mode - toggle
Recompile all widgets
Show table header - toggle
Search show original index - toggle
Layout mode fade bgr - toggle
Normal mode - toggle
None
Lock layout - toggle
Settings save
Snap - toggle
54:01.563 I [JavaFX-Launcher] jnativehook - Library extracted successfully: /home/janek/daten/projects/player/working dir/user/tmp/libJNativeHook-2.0.2.so (0x8EABFBFEAA1A81C0A83F9298889A3F3A53CE0A61).


JNativeHook: Global keyboard and mouse hooking for Java.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/jnativehook/

JNativeHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JNativeHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

54:01.588 I [JavaFX-Launcher] jnativehook - hook_get_auto_repeat_rate [242]: XkbGetAutoRepeatRate: 40.

54:01.588 I [JavaFX-Launcher] jnativehook - hook_get_auto_repeat_delay [288]: XkbGetAutoRepeatRate: 600.

54:01.588 I [JavaFX-Launcher] jnativehook - hook_get_pointer_acceleration_multiplier [329]: XGetPointerControl: 10.

54:01.588 I [JavaFX-Launcher] jnativehook - hook_get_pointer_acceleration_threshold [351]: XGetPointerControl: 4.

54:01.588 I [JavaFX-Launcher] jnativehook - hook_get_pointer_sensitivity [373]: XGetPointerControl: 20.

54:01.588 I [JavaFX-Launcher] jnativehook - hook_get_multi_click_time [400]: XtGetMultiClickTime: 200.

54:02.813 I [JavaFX Applicat] WidgetManager - Widget=IconBox factory update, source files available=true class files available=true
54:02.837 I [JavaFX Applicat] WidgetManager - Registering WidgetFactory IconBox IconBox class iconBox.IconBox
54:02.839 I [JavaFX Applicat] WidgetManager - Widget=Build factory update, source files available=false class files available=false
54:02.847 I [JavaFX Applicat] WidgetManager - Widget=Logger factory update, source files available=true class files available=true
54:02.865 I [JavaFX Applicat] WidgetManager - Registering WidgetFactory Logger Logger class logger.Logger
54:02.866 I [JavaFX Applicat] WidgetManager - Widget=Tagger factory update, source files available=true class files available=true
54:02.882 I [JavaFX Applicat] WidgetManager - Registering WidgetFactory Tagger Tagger class tagger.Tagger
54:02.882 I [JavaFX Applicat] WidgetManager - Widget=FileInfo factory update, source files available=true class files available=true
54:02.896 I [JavaFX Applicat] WidgetManager - Registering WidgetFactory FileInfo File Info class fileInfo.FileInfo
54:02.898 W [JavaFX Applicat] FileMonitor - Recursive file watcher is not supported, using standard, file=/home/janek/daten/projects/player/working dir/widgets
54:02.918 I [JavaFX Applicat] WidgetManager - Registered widget=File Info
54:02.918 I [JavaFX Applicat] WidgetManager - Registered widget=Empty
54:02.918 I [JavaFX Applicat] WidgetManager - Registered widget=Tagger
54:02.918 I [JavaFX Applicat] WidgetManager - Registered widget=IconBox
54:02.918 I [JavaFX Applicat] WidgetManager - Registered widget=Logger
54:02.989 E [ForkJoinPool.co] CoreSerializer - Failed to deserialize file=/home/janek/daten/projects/player/working dir/user/library/MetadatasDB to type=class sp.it.pl.audio.MetadatasDB
java.io.InvalidClassException: sp.it.pl.audio.tagging.Metadata; local class incompatible: stream classdesc serialVersionUID = 65190842318266207, local class serialVersionUID = -452282003585592349
        at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:689)
        at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1896)
        at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1765)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2053)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1587)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at java.base/java.util.HashMap.readObject(HashMap.java:1465)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
        at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2209)
        at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2080)
        at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1587)
        at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
        at sp.it.pl.service.database.Db.getAllItems(Db.kt:134)
        at sp.it.pl.service.database.Db.updateInMemoryDbFromPersisted(Db.kt:122)
        at sp.it.pl.service.database.Db$init$2.run(Db.kt:48)
        at sp.it.pl.util.async.future.Fut.lambda$then$11(Fut.java:155)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
54:03.854 I [JavaFX Applicat] WindowManager - Restored 1/1 windows.
54:03.876 I [JavaFX Applicat] Player - Activating playback
54:04.682 I [JavaFX Applicat] PluginBase - Plugin Screen Rotator starting...
54:04.707 I [JavaFX Applicat] PluginBase - Plugin Dir Search stopping...
54:04.707 I [JavaFX Applicat] PluginBase - Plugin App Search stopping...
54:04.710 I [JavaFX Applicat] ServiceBase - Service Notifications starting...
54:04.788 I [JavaFX Applicat] ServiceBase - Service Tray starting...

(java:6415): Gtk-CRITICAL **: 11:54:04.801: IA__gtk_window_resize: assertion 'height > 0' failed
54:07.958 I [JavaFX Applicat] Window - Closing main window. 1 windows currently open.
54:07.966 I [JavaFX Applicat] WindowManager - Serializing 1 application windows
```

**Comment by sghpjuikit** [comment]
Is that because of the `(java:6415): Gtk-CRITICAL **: 11:54:04.801: IA__gtk_window_resize: assertion 'height > 0' failed` error?

Or plugins simply do not load? Are you sure they are enabled in the settings > plugins > pluginX > enabled

**Comment by sghpjuikit** [comment]
I reproduced your bug.

The observed issue is that the widgets do not load properly. I do not know why there is no error in the logs, so I'm going to fix that first.

As for the issue, I'm guessing this is because of the update in XStream library. So the problem should be resolvable by deleting the files in the workingDir/user/layouts, which also means the user has to make a new layout...

To answer why the result is what it is - when the widget fails to load and empty widget is provided instead. This should be handled a little better.

**Comment by sghpjuikit** [comment]
I am also fairly sure this problem only appears on update kotlin branch. Please do not report issues that are not reproducible on master branch - they only pertain to issues with the code in the branch and are not issues.

**Comment by Xerus2000** [comment]
The reason might have been that your widgets already were compiled and never needed to be recompiled. It helps to to a `gradle clean build` now and then to detect such issues.

**Comment by sghpjuikit** [comment]
That could be the case yes, but I'm not certain of it.
